from __future__ import annotations

# Runtime utility module (imported by hooks); not a pytest test module.
__test__ = False

BASE_COMMON_PATTERNS = ("config/",)

COMMON_PATTERNS_BY_TOOL: dict[str, tuple[str, ...]] = {
    "gradle": (
        "**/build.gradle",
        "**/build.gradle.kts",
        "**/settings.gradle",
        "**/settings.gradle.kts",
        "**/gradle/libs.versions.toml",
        "**/buildSrc/**",
    ),
    "npm": (
        "**/package.json",
        "**/package-lock.json",
        "**/pnpm-lock.yaml",
        "**/yarn.lock",
        "**/npm-shrinkwrap.json",
    ),
    "python": (
        "**/pyproject.toml",
        "**/requirements*.txt",
        "**/Pipfile",
        "**/Pipfile.lock",
        "**/poetry.lock",
        "**/setup.py",
        "**/setup.cfg",
    ),
    "go": (
        "**/go.mod",
        "**/go.sum",
    ),
    "rust": (
        "**/Cargo.toml",
        "**/Cargo.lock",
    ),
    "dotnet": (
        "**/*.csproj",
        "**/*.fsproj",
        "**/*.vbproj",
        "**/Directory.Packages.props",
        "**/packages.config",
        "**/packages.lock.json",
        "**/global.json",
        "**/nuget.config",
    ),
}

DEFAULT_COMMON_PATTERNS = tuple(
    pattern for pattern in BASE_COMMON_PATTERNS + sum(COMMON_PATTERNS_BY_TOOL.values(), ())
)

DEFAULT_CODE_PATHS = (
    "src",
    "app",
    "apps",
    "modules",
    "packages",
    "service",
    "services",
    "backend",
    "frontend",
    "lib",
    "libs",
    "server",
    "client",
    "core",
    "domain",
    "shared",
    "python",
    "java",
    "kotlin",
    "cmd",
    "pkg",
    "internal",
    "crates",
)

DEFAULT_CODE_EXTENSIONS = (
    ".kt",
    ".kts",
    ".java",
    ".groovy",
    ".gradle",
    ".gradle.kts",
    ".scala",
    ".swift",
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hpp",
    ".cs",
    ".csproj",
    ".fs",
    ".fsx",
    ".fsproj",
    ".fsharp",
    ".vb",
    ".vbproj",
    ".go",
    ".rb",
    ".rs",
    ".py",
    ".pyi",
    ".pyx",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".m",
    ".mm",
    ".php",
    ".dart",
    ".mjs",
    ".cjs",
    ".hs",
    ".erl",
    ".ex",
    ".exs",
    ".cls",
)

DEFAULT_CODE_FILES = (
    "build.gradle",
    "build.gradle.kts",
    "settings.gradle",
    "settings.gradle.kts",
    "gradle/libs.versions.toml",
    "pom.xml",
    "package.json",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "npm-shrinkwrap.json",
    "pyproject.toml",
    "requirements.txt",
    "pipfile",
    "pipfile.lock",
    "poetry.lock",
    "setup.py",
    "setup.cfg",
    "go.mod",
    "go.sum",
    "cargo.toml",
    "cargo.lock",
    "directory.packages.props",
    "packages.config",
    "packages.lock.json",
    "global.json",
    "nuget.config",
)
