name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      repository:
        description: "Target repository (pypi or testpypi)"
        required: false
        type: choice
        default: pypi
        options:
          - pypi
          - testpypi

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build backend
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build distributions
        run: python -m build

      - name: Determine publish target
        id: target
        run: |
          target="${{ github.event.inputs.repository }}"
          if [ -z "$target" ]; then
            target="pypi"
          fi
          echo "target=$target" >> "$GITHUB_OUTPUT"

      - name: Publish to PyPI
        if: steps.target.outputs.target == 'pypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true

      - name: Publish to TestPyPI
        if: steps.target.outputs.target == 'testpypi'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
